import "dotenv/config";
import express from 'express';
import cookieParser from "cookie-parser";
// import home from "./controller/home.js";
// import user from './controller/user.js';
//import route from './routing/route.js';
import cors from 'cors';
import route from "./route/route.js";
const app = express();
const port = process.env.PORT || 7200;
app.use(cookieParser());
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(cors({credentials:true}));
app.get('/', (req, res) => {res.send('Hello World');});
app.use(route);
//app.use(route);
// app.get('/user', user.listuser);
// app.get('/home', home.home);
app.listen(port, ()=> {console.log(`Berjalan di port ${port}`);});
