import { Router } from "express";
import user from "../controller/user.js";
import mdr from "../middleware/mdr.js";
import refreshToken from "../controller/refreshToken.js";
import postingan from "../controller/postingan.js";
const route = Router();
//route.get('/user', login.checktoken, user.listuser);
route.post('/user', user.insert_dt);
route.post('/login', user.login);
route.get('/user', user.find1);
//route.get('/user', mdr.cektoken, user.find1);
route.get('/test/:id', refreshToken.refresh);
route.post('/posting', postingan.insert_content);
route.get('/posting', postingan.get_content);
route.get('/posting3', mdr.cektoken, postingan.get_content);
route.get('/posting2/:id', mdr.cektoken, postingan.update_content1);
//route.post('/posting2', postingan.update_content1);
route.patch('/posting/:id', postingan.update_content);
route.patch('/posting2/:id', postingan.update_content2);
route.delete('/logout', user.logout);
//route.get('/test', user.find1);
export default route;